name: Danger
run-name: ${{ github.workflow }}-${{ github.actor }}-${{ github.event.head_commit.message}}

on:
  pull_request:
    types: [ opened, edited, reopened, synchronize ]
jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
      - name: Check out actions
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: yarn

      - uses: danger/danger-js@11.2.0
        name: Danger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

