name: Lint
run-name: ${{ github.workflow }}-${{ github.actor }}-${{ github.event.head_commit.message}}
on:
  push:
    branches:
      - ci_cd
      - feat/authTests
      - refactoring/initialVersion
  pull_request:
    branches:
      - master
jobs:
  run-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install Dependencies
        run: yarn

      - name: Run Linter
        run: yarn lint
